### PR TITLE
Putio Files.download fails because Client::get adds a ? at the end of the URL even when query params is empty.

### PR DESCRIPTION
**Pull request by ptheofan**

### CODE REVIEW

**Comment by mozammil** [comment]
@ptheofan Thank you for submitting the PR. However, this project hasn't been touched in a long time and I can also see that this particular endpoint is deprecated? 

https://app.swaggerhub.com/apis-docs/putio/putio/2.8.2#/files/get_files__id__download

It also seems to me they no longer return a response body, or am I mistaken? :)

**Comment by ptheofan** [comment]
Applying the fix actually makes the endpoint work. Basic file operations that I tried appear to be working fine

**Comment by mozammil** [comment]
@ptheofan Could you then explain what the changes do? In my opinion we should already receive a downloadable url which the Guzzle client should be able to work with, or?

**Comment by ptheofan** [comment]
Basically breakes putio download URL to host and query params for the Client::get function that follows. However the issue was a bit deeper at the Client::get itself. (I've updated the PR)

Your Client::get was always adding a `?` at the end of a URL even if query params were not provided.
Files::download provides a full URL (with params). Client::get was adding an extra `?` at the end of the URL breaking the URI structure.

**Comment by ptheofan** [comment]
I have discovered more API parts that are no longer compatible with putio REST API so I'm afraid I'm gonna drop the library for my personal little project and just go directly with the rest API.

You might want to consider marking the library as deprecated?

Cheers.

**Pull request closed without merging**
